import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Written out rather than autogenerated. The reading order matters here —
// someone arriving at this site has a GPU and no working endpoint, and the
// order below is the order that gets them one.

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'install',
    'skill',
    'quickstart',
    {
      type: 'category',
      label: 'Hosts',
      items: ['hosts/h1-nvidia', 'hosts/h2-amd', 'hosts/adding-a-host'],
    },
    {
      type: 'category',
      label: 'Models',
      items: ['models/catalog', 'models/adding-a-model', 'models/schema'],
    },
    {
      type: 'category',
      label: 'Control host',
      items: ['control-host/pi', 'control-host/claude-code', 'control-host/opencode'],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/monitoring',
        'operations/tailscale',
        'operations/troubleshooting',
        'operations/stacklog',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/make-targets', 'reference/stacklog-schema', 'reference/roadmap'],
    },
  ],
};

export default sidebars;
